### ISSUE TITLE
Xamarin.Forms `^base` selector isn't compiled properly

### ISSUE THREAD

**Issue by samhouts** [madskristensen/LessCompiler#22]
### Installed product versions
- Visual Studio: 16.7.0 Preview 2.0
- This extension: 0.9.46

### Description
Xamarin.Forms has its own selector to allow you to style any element with a base class matching the class. LessCompiler adds a space between the ^ and the class name.

### Steps to recreate
Add a style like so: 
```css
^contentpage {
    background-color: red;
}
```

Save.

### Current behavior
.css:

 ```css
^ contentpage {
  background-color: red;
}
```

### Expected behavior
.css:

 ```css
^contentpage {
  background-color: red;
}
```
